### ISSUE TITLE
Cannot build on ubuntu 18.04

### ISSUE THREAD

**Issue by thefloppydriver** [Coding-Bunker/unofficial-discord-client#18]
The error is 
```/home/thefloppydriver/discord_light/unofficial-discord-client/src/handlers/Requester.cpp:23:6:` error: prototype for ‘void Requester::handleGuilds()’ does not match any in class ‘Requester’
 void Requester::handleGuilds()
      ^~~~~~~~~
In file included from /home/thefloppydriver/discord_light/unofficial-discord-client/src/handlers/Requester.cpp:1:0:
/home/thefloppydriver/discord_light/unofficial-discord-client/src/handlers/Requester.hpp:21:10: error: candidate is: void Requester::handleGuilds(QVariant)
     void handleGuilds(QVariant dummy);
          ^~~~~~~~~~~~
src/CMakeFiles/unofficial-discord-client.dir/build.make:134: recipe for target 'src/CMakeFiles/unofficial-discord-client.dir/handlers/Requester.cpp.o' failed
make[2]: *** [src/CMakeFiles/unofficial-discord-client.dir/handlers/Requester.cpp.o] Error 1
CMakeFiles/Makefile2:86: recipe for target 'src/CMakeFiles/unofficial-discord-client.dir/all' failed
make[1]: *** [src/CMakeFiles/unofficial-discord-client.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2```

Please help? I don't know what this means, Also please add a pre-built release as a .zip file so that people can use this without having to go through the trouble of building.

**Comment by guerinoni** [comment]
@thefloppydriver 
Sorry for late, try now in master branch :D

**Comment by guerinoni** [comment]
@thefloppydriver 
Have you some news?
